version: '3'
services:
  back-end:
    build:
      context: .
      dockerfile: dockerfile-backend
    ports:
      - "3000:3000"
    networks:
      - mi-red
    container_name: express-angular-dockerfiles-back-end
  front-end:
    build:
      context: .
      dockerfile: dockerfile-frontend
    ports:
      - "4200:4200"
    networks:
      - mi-red
    container_name: express-angular-dockerfiles-front-end
networks:
  mi-red:
    name: mi-red